king_of_uni/group/urls.py
from django.urls import path

from group.views import (
    create_group_view,
    join_group_view,
    group_view,
    leave_group_view,
)

app_name = 'group'

urlpatterns = [
    path('', group_view, name="group_info"),
    path('join_group/', join_group_view, name="join_group"),
    path('leave_group/', leave_group_view, name="leave_group"),
]

king_of_uni/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from personal.views import (
    home_screen_view,
    rules_screen_view,
    leaderboard_view,
    privacy_policy_view
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name = "home"),
    path('rules/',rules_screen_view, name = "rules"),
    path('leaderboard', leaderboard_view, name="leaderboard"),
    path('register/', registration_view, name = "register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('privacy/', privacy_policy_view, name="privacy"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('game_keeper/', include('gameKeeper.urls', 'game_keeper')),
    path('territory_game/', include('territoryGame.urls', 'territory_game')),
    path('group/', include('group.urls', 'group')),


    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

king_of_uni/territoryGame/urls.py
from django.urls import path

from territoryGame.views import (
    territories_view,
    detail_territory_view,
)

app_name = 'territory_game'

urlpatterns = [
    path('', territories_view, name="territories"),
    path('<slug>/', detail_territory_view, name="detail_territory"),
]

king_of_uni/territoryGame/models.py
"""
Provides model for Territory capture
"""
from django.db import models
from gameKeeper.models import Building
from account.models import Account
from group.models import Group

__author__ = "Jakupov Dias"

# Create your models here.
class TerritoryCapture(models.Model):
    comment             = models.CharField(max_length=200, blank= True)
    territory_name      = models.ForeignKey(Building, verbose_name="Territories", default = 0, on_delete=models.SET_DEFAULT)
    team                = models.ForeignKey(Group, verbose_name="Holder", null=True, default = None, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return self.territory_name.name

king_of_uni/territoryGame/forms.py
"""Provides forms for Capturing the territory
CreateTerritoryCaptureForm - form for creating new territory capture
UserLocationForm - form for saving user location
"""
from django import forms
from territoryGame.models import TerritoryCapture
from account.models import Account

__author__ = "Jakupov Dias"

class CreateTerritoryCaptureForm(forms.ModelForm):

    class Meta:
        model = TerritoryCapture
        fields = ['comment']

class UserLocationForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ['latitude', 'longitude']

king_of_uni/territoryGame/views.py
"""
Provides Views for territories, detail_territory
"""
from warnings import catch_warnings
from django import forms
from django.shortcuts import render, redirect, get_object_or_404
from account.models import Account
from gameKeeper.models import Building
from territoryGame.models import TerritoryCapture
from territoryGame.forms import CreateTerritoryCaptureForm, UserLocationForm
from .utils import get_center_coordinates, get_zoom
from django.contrib import messages
import folium
from geopy.distance import geodesic
import decimal
from datetime import datetime, timedelta
from django.utils import timezone

__author__ = "Jakupov Dias, Edward Calonghi"

# Create your views here.
def territories_view(request):
    context = {}

    if not request.user.is_authenticated:
        return redirect('login')

    buildings = Building.objects.all()

    context['buildings'] = buildings

    
    return render(request, 'territoryGame/territories.html', context)

def detail_territory_view(request, slug):

    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('login')

    building = get_object_or_404(Building, slug=slug)

    #destindation coordinates

    building_latitude = building.latitude
    building_longitude = building.longitude

    #foliun map modificatiom
    map = folium.Map(location = get_center_coordinates(building_latitude, building_longitude), zoom_start = 15)
    
    #building marker
    folium.Marker(location = [building_latitude, building_longitude],
                    tooltip='Click for the name', popup=building.buildingInfo(),
                    icon=folium.Icon(color='blue',icon='info-sign')).add_to(map)
                    

    if 'showLocation' in request.POST:
        form = UserLocationForm(request.POST)
        if form.is_valid():
            latitude = request.POST['latitude']
            longitude = request.POST['longitude']
            user.latitude = latitude
            user.longitude = longitude
            user.save()
            #distance calculation
            pointA = (building_latitude,building_longitude)
            pointB = (latitude, longitude)
            distance = round(geodesic(pointA,pointB).meters)
            map = folium.Map(location = get_center_coordinates(building_latitude, building_longitude, decimal.Decimal(latitude), decimal.Decimal(longitude)), zoom_start = get_zoom(distance))
            #building marker
            folium.Marker(location = [building_latitude, building_longitude],
                    tooltip='Click for the name', popup=building.name,
                    icon=folium.Icon(color='blue',icon='info-sign')).add_to(map)
            #user marker
            folium.Marker(location = [latitude, longitude],
                    tooltip='Click for the name', popup="Distance to " + building.name + " is " + str(distance) + "m",
                    icon=folium.Icon(color='red', icon='cloud')).add_to(map)
            #draw line between user and building
            line = folium.PolyLine(locations = [pointA, pointB], weight=2, clolor='red')
            map.add_child(line)
            if distance < 200:
                context['enable'] = True
                messages.success(request, 'You can capture the territory') 
            else:
                messages.error(request, 'You are too far from the territory') 
    map = map._repr_html_()

    if 'capture' in request.POST:
        form = CreateTerritoryCaptureForm(request.POST)
        # check the builidings capture date to see if it was recently captured if
        # the building has no cature date the check is bypassed
        try:
            elapesed_time = timezone.now() - building.capture_date
            cooldown = timedelta(hours=24)
        except:
            elapesed_time = 1
            cooldown = 0
        print(elapesed_time)
        print(cooldown)
        if elapesed_time > cooldown:
            if form.is_valid():
                obj = form.save(commit=False)
                username = Account.objects.filter(username = request.user.username).first()
                obj.team = username.belongs_to_group
                obj.territory_name = building
                obj.save()
                form = CreateTerritoryCaptureForm
                if str(building.holder) == str(user.belongs_to_group):
                    # saves data in the Building model
                    building.is_captured = True
                    building.holder = user.belongs_to_group.name
                    building.capture_date = datetime.now()
                    building.streak *= 2
                    building.save()
                    # adds points to user and saves data in Account model
                    user.score += 20
                    user.save()
                    # adds user points to teams points and saves data in Group Model
                    group = user.belongs_to_group
                    group.point_total += 10 * building.streak
                    group.save()                
                else:
                    # saves data in the Building model
                    building.is_captured = True
                    building.holder = user.belongs_to_group.name
                    building.capture_date = datetime.now()
                    building.streak = 1
                    building.save()
                    # adds points to user and saves data in Account model
                    user.score += 10
                    user.save()
                    # adds user points to teams points and saves data in Group Model
                    group = user.belongs_to_group
                    group.point_total += 10
                    group.save()
                return redirect('territory_game:territories')
        else:
            messages.error(request, 'Territory still on cooldown: '+str(cooldown - elapesed_time)+' left')
    else:
        form = CreateTerritoryCaptureForm()      
        
    context['form'] = form
    context['building'] = building
    context['map'] = map
    return render(request, 'territoryGame/detail_territory.html', context)

king_of_uni/territoryGame/templates/territoryGame/detail_territory.html
{% extends 'base.html' %}


{% block content %}


<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			{% if request.user.is_inTeam %}
				<form class="create-form" method="post">{% csrf_token %}

			
				<div class="form-group">
					<h2 class="card-title">{{building.name}}</h2>
				</div>

				<div class="form-group">
					{{map | safe}}
				</div>

				<div class="form-group">
					<label for="id_comment">Comment</label>
					<input class="form-control" type="text" name="comment" id="id_comment" placeholder="Comment">
				</div>
				<input type="hidden" id="latitude" name="latitude" value="">
				<input type="hidden" id="longitude" name="longitude" value="">
				<p id="demo"></p>
				{% for message in messages %}
					{% if message.tags == "error" %}
						<div style="color:rgb(255, 0, 0)">
							<p>{{ message|safe }}</p>
						</div>
					{% else %}
						<div style="color:rgb(0, 255, 64)">
							<p>{{ message|safe }}</p>
						</div>
					{% endif %}
				{% endfor %}


					<!-- Submit btn -->
					<button class="submit-button btn btn-lg btn-primary btn-block" type="submit" name="showLocation" id="location" onclick="unlockButton();" disabled>Show my location</button>
					<button class="submit-button btn btn-lg btn-primary btn-block" type="submit" name="capture" id="capture" {% if not enable %} disabled {%endif%}>Capture</button>
				</form>	
			{% else %}
				<p>You are not in a team. You should <a href="{% url 'group:join_group' %}">join a team</a>to capture territories.</p>
			{% endif %}
		</div>
	</div>
</div>


<script>    
	var x = document.getElementById("latitude");
	var y = document.getElementById("longitude");
	var demo = document.getElementById("demo");

	function getLocation() {
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(showPosition);
		} else { 
			alert("Sorry, your browser does not support HTML5 geolocation.");
		}
	}

	function showPosition(position) {
		navigator.geolocation.getCurrentPosition(function(position) {
			x.value = position.coords.latitude;
			y.value = position.coords.longitude;
		    document.getElementById("location").disabled = false;
		});
	}	
	window.onload=getLocation;

  </script>

{% endblock content %}

king_of_uni/territoryGame/templates/territoryGame/territories.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
    .buildings{
      max-width: 500px;
      width: 100%;
      margin: auto;
    }
  </style>

{% if request.user.is_authenticated %}
<div class="container mt-4 p-4">
    <div class="row">
      <div class="buildings">
        {% if request.user.is_inTeam %}
        <h3 class="mb-3 font-weight-normal">Territories:</h3>
        {% if buildings %}
            <ul class="list-group">
            {% for building in buildings %}
              {% if building.is_active %}
                {% if building.is_captured %}
                <a class="closeBtn" href="{% url 'territory_game:detail_territory' building.slug %}" style="text-decoration: none; color: rgb(255, 0, 0);">
                  <li class="list-group-item">{{building}} | Captured</li>
                {% else %}
                <a class="closeBtn" href="{% url 'territory_game:detail_territory' building.slug %}" style="text-decoration: none; color: rgb(0, 255, 149);">
                    <li class="list-group-item">{{building}} | Not Captured</li>
                {% endif %}
              {% endif %}
            {% endfor %}
            </ul>
          {% else %}
            <p>No Territories available.</p>
          {% endif %}
        {% else %}
          <p>You are not in a team. You should <a href="{% url 'group:join_group' %}">join a team to capture territories</a>.</p>
        {% endif %}
      </div>
    </div>
  </div>




{% endif %}
{% endblock content %}