king_of_uni/gameKeeper/urls.py
from django.urls import path

from gameKeeper.views import (
    create_building_view,
    detail_building_view,
    game_keeper_view,
)

from group.views import (
    groups_list_view,
    create_group_view,
)

app_name = 'game_keeper'

urlpatterns = [
    path('create_group/', create_group_view, name="create_group"),
    path('group/', groups_list_view, name="groups_list"),
    path('settings/', game_keeper_view, name="settings"),
    path('create/', create_building_view, name="create"),
    path('<slug>/', detail_building_view, name="detail"),
]

king_of_uni/group/urls.py
from django.urls import path

from group.views import (
    create_group_view,
    join_group_view,
    group_view,
    leave_group_view,
)

app_name = 'group'

urlpatterns = [
    path('', group_view, name="group_info"),
    path('join_group/', join_group_view, name="join_group"),
    path('leave_group/', leave_group_view, name="leave_group"),
]

king_of_uni/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from personal.views import (
    home_screen_view,
    rules_screen_view,
    leaderboard_view,
    privacy_policy_view
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name = "home"),
    path('rules/',rules_screen_view, name = "rules"),
    path('leaderboard', leaderboard_view, name="leaderboard"),
    path('register/', registration_view, name = "register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('privacy/', privacy_policy_view, name="privacy"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('game_keeper/', include('gameKeeper.urls', 'game_keeper')),
    path('territory_game/', include('territoryGame.urls', 'territory_game')),
    path('group/', include('group.urls', 'group')),


    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

king_of_uni/territoryGame/urls.py
from django.urls import path

from territoryGame.views import (
    territories_view,
    detail_territory_view,
)

app_name = 'territory_game'

urlpatterns = [
    path('', territories_view, name="territories"),
    path('<slug>/', detail_territory_view, name="detail_territory"),
]

king_of_uni/templates/snippets/footer.html
<style type=text/css>
    .footer{
        min-height: 100px
    }
</style>
<hr>
<div class="d-flex flex-row align-items-center footer">
    <p class="m-auto">King of Uni | 2022</p>
  <!-- Button trigger modal -->
  <p class="m-auto"><a data-toggle="modal" href='#exampleModalLong'>Privacy Policy</a></p>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Privacy Policy</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="lead">
              This application does collect certain personal data, this includes the email, username and
              location (kept as longitude and latitude) when 'Show My Location' is pressed on the
              territory screen. Any passwords, however, are not retained in plaintext and instead kept
              in hashed form.
        </p>
        <p class="lead">
              The longitude and latitude of a user are retained until another location is entered,
              deleting the previous.
        </p>
        <p class="lead">
              No data collected by this application is shared in any capacity, and is collected
              strictly for use within the application.
        </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    

king_of_uni/templates/snippets/header.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<style>
@media (min-width: 768px) {
  html {
    font-size: 16px;
  }
}

.container {
  max-width: 960px;
}

.pricing-header {
  max-width: 700px;
}

.card-deck .card {
  min-width: 220px;
}

.border-top { border-top: 1px solid #e5e5e5; }
.border-bottom { border-bottom: 1px solid #e5e5e5; }
.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

.head {
  position: sticky;
}

</style>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow head">
  <h5 class="my-0 mr-md-auto font-weight-normal">
    {% if request.user.is_authenticated %}
    <img src="{% static 'KoU_logo.png' %}" width="40" height="40">
    {% endif %}
  </h5>
  <nav class="my-2 my-md-0 mr-md-3" ml-auto>
    {% if request.user.is_authenticated %}
      {% if request.user.is_gameKeeper %}
        <a class="p-2 text-dark" href="{% url 'home' %}">Home</a> 
        <a class="p-2 text-dark" href="{% url 'game_keeper:settings' %}">Game settings</a> 
        <a class="p-2 text-dark" href="{% url 'game_keeper:groups_list' %}">Teams</a> 
        <a class="p-2 text-dark" href = "{% url 'account' %}">Account</a> 
        <a class="p-2 text-dark" href = "{% url 'logout' %}">Logout</a>
      {% else %}
        <a class="p-2 text-dark" href="{% url 'home' %}">Home</a> 
        <a class="p-2 text-dark" href="{% url 'rules' %}">Rules</a> 
        <a class="p-2 text-dark" href="{% url 'leaderboard' %}">Leaderboard</a> 
        <a class="p-2 text-dark" href="{% url 'group:group_info' %}">Teams</a> 
        <a class="p-2 text-dark" href="{% url 'territory_game:territories' %}">Territories</a>
        <a class="p-2 text-dark" href = "{% url 'account' %}">Account</a> 
        <a class="p-2 text-dark" href = "{% url 'logout' %}">Logout</a>
      {% endif %}
    {% else %}
    <a class="p-2 text-dark"  href="{% url 'home' %}">Home</a> 
    <a class="p-2 text-dark"  href="{% url 'login' %}">Login</a>
    <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a> 
    {% endif %}
  </nav>
</div>