king_of_uni/gameKeeper/urls.py
from django.urls import path

from gameKeeper.views import (
    create_building_view,
    detail_building_view,
    game_keeper_view,
)

from group.views import (
    groups_list_view,
    create_group_view,
)

app_name = 'game_keeper'

urlpatterns = [
    path('create_group/', create_group_view, name="create_group"),
    path('group/', groups_list_view, name="groups_list"),
    path('settings/', game_keeper_view, name="settings"),
    path('create/', create_building_view, name="create"),
    path('<slug>/', detail_building_view, name="detail"),
]

king_of_uni/group/urls.py
from django.urls import path

from group.views import (
    create_group_view,
    join_group_view,
    group_view,
    leave_group_view,
)

app_name = 'group'

urlpatterns = [
    path('', group_view, name="group_info"),
    path('join_group/', join_group_view, name="join_group"),
    path('leave_group/', leave_group_view, name="leave_group"),
]

king_of_uni/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from personal.views import (
    home_screen_view,
    rules_screen_view,
    leaderboard_view,
    privacy_policy_view
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name = "home"),
    path('rules/',rules_screen_view, name = "rules"),
    path('leaderboard', leaderboard_view, name="leaderboard"),
    path('register/', registration_view, name = "register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('privacy/', privacy_policy_view, name="privacy"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('game_keeper/', include('gameKeeper.urls', 'game_keeper')),
    path('territory_game/', include('territoryGame.urls', 'territory_game')),
    path('group/', include('group.urls', 'group')),


    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

king_of_uni/group/models.py
"""
Provides model for Teams (Groups)
"""
from django.db import models

__author__ = "Joseph Cato"

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=100,  null=False, blank=False, unique=True)
    date_created = models.DateTimeField(verbose_name="date created" , auto_now_add=True) 
    point_total = models.IntegerField(default=0)
    color = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.name

king_of_uni/group/forms.py
"""
Provides form for creating a Team
"""
from django import forms
from group.models import Group
from account.models import Account

__author__ = "Joseph Cato"

class CreateGroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ['name']


        

king_of_uni/group/views.py
"""
Provides views for creating and joining grouos
"""
from django.shortcuts import render, redirect
from group.forms import CreateGroupForm
from group.models import Group
from account.models import Account
from django.contrib import messages

__author__ = "Joseph Cato"

# Create your views here.
def group_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('login')
    
    group = user.belongs_to_group
    group_members = Account.objects.filter(belongs_to_group=group).order_by('-score')
    context['members'] = group_members


    return render(request, 'group/group.html', context)

def groups_list_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('login')
    
    groups = Group.objects.all()
    context['groups'] = groups


    return render(request, 'group/groups_list.html', context)

def create_group_view(request):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('login')

    form = CreateGroupForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = CreateGroupForm()
        return redirect('game_keeper:groups_list')
    context['form'] = form
    return render(request, 'group/create_group.html', context)

def join_group_view(request):
    context = {}
    groups = Group.objects.all()
    user = request.user
    if not user.is_authenticated:
        return redirect('login')
    
    if request.POST:
        try:      
            group_name = request.POST['belongs_to_group']
            group = Group.objects.get(name=group_name)
            user.belongs_to_group = group
            user.is_inTeam = True
            user.save()
            return redirect('group:group_info')
        except Group.DoesNotExist:
            messages.error(request, 'No such group') 
    else:
        context['groups'] = groups


    return render(request, 'group/join_group.html', context)

def leave_group_view(request):
    user = request.user
    user.is_inTeam = False
    user.belongs_to_group = None
    user.save()
    return redirect('group:group_info')

king_of_uni/group/templates/group/create_group.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
              <form class="create-form" method="post">{% csrf_token %}
  
             
                <div class="form-group">
                    <label for="id_title">Name of the Group</label>
                    <input class="form-control" type="text" name="name" id="id_name" placeholder="Name" required autofocus>
                </div>
  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Create Group</button>
              </form>	
          </div>
      </div>
  </div>

{% endblock content %}

king_of_uni/group/templates/group/group.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
    .buildings{
      max-width: 500px;
      width: 100%;
      margin: auto;
    }
  </style>

{% if request.user.is_authenticated %}
<div class="container mt-4 p-4">
        {% if request.user.is_inTeam %}
        <h3 class="mb-3 font-weight-normal">Leaderboard of {{request.user.belongs_to_group}} team</h3>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">User</th>
              <th scope="col">Score</th>
            </tr>
          </thead>
          <tbody>
          {% for member in members %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{member.username}}</td>
              <td>{{member.score}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{% url 'group:leave_group' %}">Leave your team</a>
        {% else %}
          <p>You are not in a team. <a href="{% url 'group:join_group' %}">Join a team</a>.</p>
        {% endif %}
  </div>


{% endif %}
<script>
  var i = 1;
  $('#table').find('td:nth-child(1)').each(function(){$(this).text(i++);});
</script>
{% endblock content %}

king_of_uni/group/templates/group/groups_list.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
    .buildings{
      max-width: 500px;
      width: 100%;
      margin: auto;
    }
  </style>

{% if request.user.is_authenticated %}
<div class="container mt-4 p-4">
    <div class="row">
      <div class="buildings">
        {% if groups %}
        <h3 class="mb-3 font-weight-normal">Groups</h3>
        <ul class="list-group">
          {% for group in groups %}
            <li class="list-group-item">{{group.name}}</li>
          {% endfor %}
          </ul>
        {% else %}
          <p>No teams available</p>
        {% endif %}
        <a href="{% url 'game_keeper:create_group' %}">Create new team</a>
      </div>
    </div>
  </div>


{% endif %}
{% endblock content %}

king_of_uni/group/templates/group/join_group.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-8 offset-lg-2">
              <form class="create-form" method="post">{% csrf_token %}
  
             
                <div class="form-group">
                    <select class="form-control" name="belongs_to_group" id="cars">
                        {% for group in groups %}
                        <option value="{{group.name}}">{{group.name}}</option>
                        {% endfor %}
                      </select>
                </div>
                {% for message in messages %}
				{% if message.tags == "error" %}
					<div style="color:rgb(255, 0, 0)">
                		<p>{{ message|safe }}</p>
        			</div>
				{% endif %}
			{% endfor %}
  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Join Group</button>
              </form>	
          </div>
      </div>
  </div>

{% endblock content %}