king_of_uni/gameKeeper/urls.py
from django.urls import path

from gameKeeper.views import (
    create_building_view,
    detail_building_view,
    game_keeper_view,
)

from group.views import (
    groups_list_view,
    create_group_view,
)

app_name = 'game_keeper'

urlpatterns = [
    path('create_group/', create_group_view, name="create_group"),
    path('group/', groups_list_view, name="groups_list"),
    path('settings/', game_keeper_view, name="settings"),
    path('create/', create_building_view, name="create"),
    path('<slug>/', detail_building_view, name="detail"),
]

king_of_uni/group/urls.py
from django.urls import path

from group.views import (
    create_group_view,
    join_group_view,
    group_view,
    leave_group_view,
)

app_name = 'group'

urlpatterns = [
    path('', group_view, name="group_info"),
    path('join_group/', join_group_view, name="join_group"),
    path('leave_group/', leave_group_view, name="leave_group"),
]

king_of_uni/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from personal.views import (
    home_screen_view,
    rules_screen_view,
    leaderboard_view,
    privacy_policy_view
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name = "home"),
    path('rules/',rules_screen_view, name = "rules"),
    path('leaderboard', leaderboard_view, name="leaderboard"),
    path('register/', registration_view, name = "register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('privacy/', privacy_policy_view, name="privacy"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('game_keeper/', include('gameKeeper.urls', 'game_keeper')),
    path('territory_game/', include('territoryGame.urls', 'territory_game')),
    path('group/', include('group.urls', 'group')),


    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

king_of_uni/gameKeeper/models.py
"""
Provides model for Building
"""
from datetime import datetime, tzinfo
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify

__author__ = "Rob Campbell"

class Building(models.Model):
    name 					= models.CharField(max_length=50, null=False, blank=False, unique=True)
    latitude 				= models.DecimalField(max_digits=20, decimal_places=15, null=False, blank=False)
    longitude 				= models.DecimalField(max_digits=20, decimal_places=15, null=False, blank=False)
    streak                  = models.DecimalField(max_digits=1,decimal_places=0, default=1)
    is_active               = models.BooleanField(default=False)
    is_captured             = models.BooleanField(default=False)
    holder                  = models.CharField(max_length=50, default='Nobody')
    capture_date            = models.DateTimeField(blank=True, null=True)
    slug 					= models.SlugField(blank=True, unique=True)

    def buildingInfo(self):
        return self.name + " - held by: " + self.holder 
    def __str__(self):
	    return self.name




def pre_save_building_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.name)

pre_save.connect(pre_save_building_receiver, sender=Building)

king_of_uni/gameKeeper/forms.py
"""Provides forms for Creating Building
CreateBuildingForm - form for creating new building
"""
from dataclasses import field
from django import forms
from gameKeeper.models import Building

__author__ = "Jakupov Dias"

class CreateBuildingForm(forms.ModelForm):

    class Meta:
        model = Building
        fields = ['name', 'latitude', 'longitude']

king_of_uni/gameKeeper/views.py
"""
Provides Views for game_keeper, create_building, detail_building
"""
from django.shortcuts import render, redirect, get_object_or_404
from gameKeeper.models import Building
from gameKeeper.forms import CreateBuildingForm
import folium

__author__ = "Jakupov Dias, Rob Campbell"

def game_keeper_view(request):
    context = {}

    if not request.user.is_authenticated:
        return redirect('login')

    buildings = Building.objects.all()

    context['buildings'] = buildings

    
    return render(request, 'game_keeper/settings.html', context)

def create_building_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('login')
    form = CreateBuildingForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = CreateBuildingForm()
        return redirect('game_keeper:settings')
    context['form'] = form
    return render(request, 'game_keeper/create_building.html', context)

def detail_building_view(request, slug):
    context = {}

    building = get_object_or_404(Building, slug=slug)
    #foliun map modificatiom
    map = folium.Map(location = [50.738099451637, -3.53507522602482], zoom_start = 15)
    #building marker
    folium.Marker(location = [building.latitude, building.longitude],
                    tooltip='Click for the name', popup=building.name).add_to(map)

    map = map._repr_html_()
    #activating building
    if 'activate' in request.POST:
        building.is_active = True
        building.save()
        return redirect('game_keeper:settings')
    #deactivating building
    if 'deactivate' in request.POST:
        building.is_active = False
        building.save()
        return redirect('game_keeper:settings')
    context['building'] = building
    context['map'] = map
    return render(request, 'game_keeper/detail_building.html', context)

king_of_uni/gameKeeper/templates/game_keeper/create_building.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
              <form class="create-form" method="post">{% csrf_token %}
  
             
                <div class="form-group">
                    <label for="id_title">Name</label>
                    <input class="form-control" type="text" name="name" id="id_name" placeholder="Name" required autofocus>
                </div>
                <div class="form-group">
                    <div id="map" style="width:800px; height: 500px;"></div>
                </div>

                <input class="form-control" type="hidden" name="latitude" id="id_latitude" placeholder="Latitude" required autofocus>

                <input class="form-control" type="hidden" name="longitude" id="id_longitute" placeholder="Longitutde" required autofocus>
                {% for field in form %} 
                <p> 
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </p>
                {% endfor %}
        
                {% if form.non_field_errors %}
                <div style="color:red">
                        <p>{{form.non_field_errors}}</p>
                </div>
                {% endif %}
  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Add</button>
              </form>	
          </div>
      </div>
  </div>
  <script>
    var x = document.getElementById("id_latitude");
    var y = document.getElementById("id_longitute");
    var coords = [50.738099451637, -3.53507522602482]; // the geographic center of our map
    var zoomLevel = 16; // the map scale. See: http://wiki.openstreetmap.org/wiki/Zoom_levels
    
    var map = L.map('map').setView(coords, zoomLevel);
    

    L.tileLayer('https://api.maptiler.com/maps/openstreetmap/{z}/{x}/{y}.jpg?key=6IL7Ect5nCzx8XYDNjsN', {
        attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
        id: 'mapbox.streets'
    }).addTo(map);
    var marker = L.marker([50.738099451637, -3.53507522602482]).addTo(map);

    map.on('click', addMarker);
    function addMarker(e){
        // Add marker to map at click location; add popup window
        var lat = e.latlng.lat;
        var lng = e.latlng.lng;
        marker.setLatLng([lat, lng]); 
        x.value = lat.toFixed(5);
        y.value = lng.toFixed(5);
    }
</script>
{% endblock content %}

king_of_uni/gameKeeper/templates/game_keeper/detail_building.html
{% extends 'base.html' %}


{% block content %}


<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post">{% csrf_token %}

		   
			  <div class="form-group">
				<h2 class="card-title">{{building.name}}</h2>
			  </div>

			  <div class="form-group">
				{{map | safe}}
			  </div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit" name="activate">Activate</button>
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit" name="deactivate">Deactivate</button>
			</form>	
		</div>
	</div>
</div>

	

{% endblock content %}

king_of_uni/gameKeeper/templates/game_keeper/settings.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
    .buildings{
      max-width: 500px;
      width: 100%;
      margin: auto;
    }
  </style>

{% if request.user.is_authenticated %}
<div class="container mt-4 p-4">
    <div class="row">
      <div class="buildings">
        <h3 class="mb-3 font-weight-normal">Territories:</h3>
        {% if buildings %}
          <ul class="list-group">
          {% for building in buildings %}
            {% if building.is_active %}
            <a href="{% url 'game_keeper:detail' building.slug %}" style="text-decoration: none; color: chartreuse;">
              <li class="list-group-item">{{building}}</li></a>
            {% else %}
            <a href="{% url 'game_keeper:detail' building.slug %}" style="text-decoration: none; color: crimson;">
              <li class="list-group-item">{{building}}</li></a>
            {% endif %}
          {% endfor %}
          </ul>
        {% else %}
          <p>You have no Territories. Create a territory <a href="{% url 'game_keeper:create' %}">here</a>.</p>
        {% endif %}
        <a href="{% url 'game_keeper:create' %}">Create new territory</a>
      </div>
    </div>
  </div>


{% endif %}
{% endblock content %}